version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types: ["patch"]

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
