name: Run

on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true
    - name: Run tests
      env:
        SLACK_POST_URL: ${{ secrets.SLACK_POST_URL }}
        ARENA_ACCESS_TOKEN: ${{ secrets.ARENA_ACCESS_TOKEN }}
        RACK_ENV: ${{ secrets.RACK_ENV }}
      run: bundle exec rake
